openapi: 3.0.1
info:
  title: Steam Plugin
  description: A plugin that allows to search for games and see information about a game.
  version: 'v1'
servers:
  - url: http://localhost:5003
paths:
  /game/{id}:
    get:
      operationId: getGame
      summary: Returns information about a game
      parameters:
      - in: path
        name: id
        schema:
            type: integer
        required: true
        description: The steam game id
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/game'
  /search/name/{name}:
    get:
      operationId: searchByName
      summary: Returns the ids of matching games
      parameters:
      - in: path
        name: name
        schema:
            type: string
        required: true
        description: The Steam game name
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gameResults'
  /search/tags/{tags}:
    get:
      operationId: searchByTags
      summary: Returns the ids of matching games
      parameters:
      - in: path
        name: tags
        schema:
            type: string
        required: true
        description: Steam game tags
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gameResults'
  /search/genres/{genres}:
    get:
      operationId: searchByGenres
      summary: Returns the ids of matching games
      parameters:
      - in: path
        name: genres
        schema:
            type: string
        required: true
        description: Steam genres
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gameResults'

components:
  schemas:
    game:
      type: object
      properties:
        steam_appid:
          type: integer
          description: The ID of the game on Steam.
        name:
          type: string
          description: The name of the game.
        developers:
          type: array
          items:
            type: string
          description: The developers of the game.
        publishers:
          type: array
          items:
            type: string
          description: The publishers of the game.
        platforms:
          type: object
          properties:
            windows:
              type: boolean
            mac:
              type: boolean
            linux:
              type: boolean
          description: The platforms the game is available on.
        price_overview:
          type: object
          properties:
            currency:
              type: string
            initial:
              type: integer
            final:
              type: integer
            discount_percent:
              type: integer
          description: Overview of the game's price.
        demos:
          type: array
          items:
            type: object
            properties:
              appid:
                type: integer
              description:
                type: string
          description: Available demos of the game.
        genres:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              description:
                type: string
          description: Genres of the game.
        recommendations:
          type: object
          properties:
            total:
              type: integer
          description: Total number of recommendations.
        achievements:
          type: object
          properties:
            total:
              type: integer
            highlighted:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                  path:
                    type: string
          description: Achievements related to the game.
      required:
        - steam_appid
        - name
        - developers
        - publishers
        - platforms
        - price_overview
        - demos
        - genres
        - recommendations
        - achievements
    gameResults:
      type: object
      required:
      - matches
      properties:
        matches:
          type: array
          description: Matching games for this search request
          required: true